---
# tasks file for new-role

- name: Install Apache HTTP Webserver
  apt:
    name: apache2
    state: present
  when: ansible_os_family == "Debian"

- name: Install Apache HTTP Webserver
  yum:
    name: httpd
    state: present
  when: ansible_os_family == "RedHat"


...